version: '3.8'

services:
  nextjs:
    container_name: tattoo_app
    build: .
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
      - /app/node_modules
    restart: always